# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  host: "localhost:3000"
  firebase_key: ""
  secret_key_base: d522e62018cfc26f5d36bfeddc728b86a80c50a0b03bd3e2a383086976cf77f78e1cceeccdbe49a4974a2f6f8d0b85aea8e98722e060623c76e3fcbbdd0671b0
  stripe_secret: <%= ENV.fetch( "STRIPE_SECRET_KEY" ,"sk_test_jEqqFTaEIr5d2rGn5di9ghcT") %>
  stripe_public: <%= ENV.fetch( "STRIPE_PUBLIC_KEY" ,"pk_test_6YjbSqtBimrVOeRNngdNy3Gu") %>
  mailgun_user: "dev@mg.scheduleless.com"
  mailgun_password: "VxYbuftwmSoE9jFzbTmh"
  mixpanel: "189e2353a4bd8ab8ebd4545839d67972"
  push_enabled: "false"
  reamaze: ""
  s3_access_key: ""
  s3_bucket: ""
  s3_region: ""
  s3_secret: ""
  twilio_sid: "ACdc9a95e533039fe57753f31a8bf945b1"
  twilio_token: "a32df368b56b1d413480dde44edb6ebc"
  twilio_from_number: "+15005550006"

test:
  secret_key_base: ab6b4ba9ea75c1a0a91c1bdcd75d51be3fb0e9543a179af19b5262c90efc92c7dff28c317d7e0503212eb0c437ecc28b5b06ab7cafddf407cf99b036f44ee10b
  s3_access_key: ""
  s3_bucket: ""
  s3_region: ""
  s3_secret: ""
# Do not keep production secrets in the repository,
# instead read values from the environment.
# TODO: WHEN LAUNCHED, REMOVE THE FALLBACK TEST ENV KEYS
<% if Rails.env.production? %>
production:
  host: "scheduleless.com"
  firebase_key: <%= ENV["FIREBASE_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_secret: <%= ENV.fetch("STRIPE_SECRET_KEY") %>
  stripe_public: <%= ENV.fetch("STRIPE_PUBLIC_KEY") %>
  mailgun_user: <%= ENV.fetch("MAILGUN_USER", "") %>
  mailgun_password: <%= ENV.fetch("MAILGUN_PASSWORD", "") %>
  mixpanel: "1b2cb02b5d39c98f49d4e3f718ba0d19"
  push_enabled: <%= ENV.fetch("PUSH_ENABLED", "") %>
  reamaze: <%= ENV.fetch("REAMAZE_SSO_KEY", "") %>
  s3_access_key: <%= ENV.fetch("S3_ACCESS_KEY") %>
  s3_bucket: <%= ENV.fetch("S3_BUCKET") %>
  s3_region: <%= ENV.fetch("S3_REGION") %>
  s3_secret: <%= ENV.fetch("S3_SECRET") %>
  twilio_sid: <%= ENV.fetch("TWILIO_SID", "") %>
  twilio_token: <%= ENV.fetch("TWILIO_TOKEN", "") %>
  twilio_from_number: <%= ENV.fetch("TWILIO_FROM_NUMBER", "") %>
<% end %>
